app.stopAjaxRequests=function(url){var url=((typeof url=='undefined')?false:url);if(!url){$(app.ajaxRequests).each(function(i,item){item.xhr.abort();});}else{$(app.ajaxRequests).each(function(i,item){if(item.url==url){item.xhr.abort();}});}
app.ajaxRequests=[];};$(window).on('beforeunload.stopAjaxRequests',function(){app.stopAjaxRequests();});$(document).ready(function(){if(app.notyMessages.length>0){app.notyMessages.forEach(function(v){notyMessage(v);});app.notyMessages=[];}});function initSearchWidget(searchTimer,paginatorWidget,searchFormSelector,dateListSelector,datePairSelector,searchAfterInit,preSearchCallback){var searchForm=$(searchFormSelector);searchForm.on('submit',function(){preSearchCallback();var params=paginatorWidget.getRequestParams().params;var text=$(this).find("input:text[name=search-query]").val();var lastText=searchForm.data('last-text');if(lastText&&lastText==text){return false;}
app.stopAjaxRequests(paginatorWidget.getOptions().url);searchForm.data('last-text',text);params=$.extend({},params,{text:text});paginatorWidget.setRequestParams({params:params}).reload();return false;});$('.search-group a[data-field]').on('click',function(){$('.search-group button[data-field]').attr('data-field',$(this).data('field'));$('.search-group span#field-label').html($(this).html());$('.search-group input:text[name="search-query"]').focus();if($('.search-group input:text[name="search-query"]').val()!==''){paginatorWidget.reload();}});searchForm.find('input[name="search-query"]').on('input change',function(e){clearTimeout(searchTimer);if(e.keyCode==13){searchForm.data('last-text',null);searchForm.submit();}else{searchTimer=setTimeout(function(){searchForm.submit()},500);}});$('#searchFilterClose').on('click',function(e){e.preventDefault();$(this).parent().addClass('hidden');$('#searchFilterBtn').removeClass('active');$('input[name="search-query"]').val('').change();});$('#searchFilterBtn').on('click',function(e){e.preventDefault();var $btn=$(this);var searchForm=$btn.closest('.btn-panel').parent().find(searchFormSelector);if(!searchForm.hasClass('hidden')){$btn.removeClass('active');searchForm.addClass('hidden');searchForm.find('input[name="search-query"]').val('').change();}else{$btn.addClass('active');searchForm.removeClass('hidden');searchForm.find('input[name="search-query"]').focus();}});if(dateListSelector){var dateList=$(dateListSelector);$('input[name="date-filter-list"]',dateList).parent().on('click',function(e){e.preventDefault();var datePair=$('input',this).val();if(datePair=='Pick date range'){return true;}
var params=paginatorWidget.getRequestParams().params;params=$.extend({},params,{date_pair:datePair});paginatorWidget.setRequestParams({params:params}).reload();});}
if(datePairSelector){var datePair=$(datePairSelector);$('#showDateRange',datePair).on('click',function(e){e.preventDefault();var params=paginatorWidget.getRequestParams().params;params=$.extend({},params,{date_pair:'Pick date range',from:$('#dateFilterStart',datePair).val(),to:$('#dateFilterEnd',datePair).val()});paginatorWidget.setRequestParams({params:params}).reload();})}
if(searchAfterInit){searchForm.submit();}}
function appendNoResults($table){if($table&&($table.children('tbody').children('tr').length==0||($table.children('tbody').children('tr').length==1&&$table.children('tbody').children('tr').hasClass('table-data-select')))){var $thead=$table.children('thead'),colspan="100%",notContactTable=$table.children('tbody').children('tr').length==0;var $th=$table.children('thead').find('tr:first-child > th');if($thead.length!==0&&$th.length!==0&&notContactTable){colspan=$th.length;}
var emptyHint=$table.data('empty-hint');emptyHint=emptyHint||'No search results found. Please try a different keyword or period.';$table.children('tbody').append('<tr class="empty"><td colspan="'
+colspan
+'">'+emptyHint+'</td></tr>');}}
var msgExportDisabled='You do not have a permission to export. Please contact your company administrator.';function initExportWidget(paginatorWidget,exportSelector){var directExportLim=500;var maxExport=1000000;var isSentTable=function(paginatorWidget){var url=paginatorWidget.getOptions().url;var cmd=paginatorWidget.getRequestParams().cmd;if(typeof url!=='undefined'&&typeof cmd!=='undefined'&&(url==='/online/messages/sent/ajax'&&cmd==='table')||(url==='/online/account/ajax'&&cmd==='sentTable')){return true;}
return false;};var isEventsTable=function(paginator){var url=paginator.getOptions().url;var cmd=paginator.getRequestParams().cmd;if(typeof url!=='undefined'&&typeof cmd!=='undefined'&&(url==='/online/reporting/ajax'&&cmd==='events')){return true;}
return false;};$(exportSelector).on('click',function(e){var last=paginatorWidget.getRequestParams();var counter=$('[data-crud-export-count]');var $topAlert=$('[data-widget="top-alert"]');var csrfToken=$('meta[name="csrf-token"]').attr('content');if(app.data.user&&app.data.user.exportDisabled){$topAlert.warningBlock(msgExportDisabled);$(this).closest('.btn-group').removeClass('open');return false;}
if(counter.length&&parseInt(counter.data('crud-export-count'))>maxExport){notyMessage('Your exported file is too large. Please contact support to get the requested file.',{type:'warning'});$(this).closest('.btn-group').removeClass('open');return false;}
if(typeof itemsCount!=='undefined'){if(parseInt(itemsCount)>directExportLim||isSentTable(paginatorWidget)||isEventsTable(paginatorWidget)){var options={last:last,exportLnk:$(this),maxExport:maxExport};$.confirmDefferedExport(options);return false;}}
delete last.page;var query='?'+decodeURIComponent($.param(last))
if($(this).attr('href').includes('messages_sent_ajax')||$(this).attr('href').includes('contacts_ajax')){query=query+'&_csrf_token='+encodeURIComponent(csrfToken);}
$(this).attr('href',$(this).attr('href').replace(/\?.+/,'')+query);});}
function initDateFilterWidget(){$('input:radio[name="date-filter-list"]').on('change',function(){$('#dateFilterValue').text($(this).parent().text());if(this.value=='Pick date range'){$('#dateFilter').removeClass('hidden');}else{$('#dateFilter').addClass('hidden');}});$('#dateFilterClose').on('click',function(){$(this).parent().addClass('hidden');var $all=$('input:radio[name="date-filter-list"][value="All"]').click();$('#dateFilterValue').text($all.parent().text());});}
Array.prototype.pushOnce=function(obj){if($.inArray(obj,this)===-1){this.push(obj);}};Array.prototype.popAll=function(obj){for(var i=this.length-1;i>=0;i--){if(this[i]===obj){this.splice(i,1);}}};function parseErrors(xhr,elemSelector,textElemSelector){if(typeof(xhr.data.selector)=='undefined'){$(textElemSelector).text(xhr.message);$(elemSelector).show();}else{$('<span class="help-block error">'+xhr.message+'</span>').insertAfter(xhr.data.selector);$(xhr.data.selector).closest('.form-group').addClass('has-error');}}
function parseAllErrors(errors){$.each(errors,function(key,value){var selector='input[data-field='+key+']:visible, textarea[data-field='+key+']:visible, span[data-field='+key+'], div[data-field='+key+']:visible';if(value!==null){$('<span class="help-block error">'+value+'</span>').insertAfter(selector);}
$(selector).closest('.form-group').addClass('has-error');});};function spinIt($container,value){if($container.find('table').length>1){$container.spin(value)}
else{$container.find('table').spin(value);}}
function hideErrors(elemSelector){$('span.error').not('.tag-item').remove();$('.has-error').removeClass('has-error');$('.has-success').removeClass('has-success');$(elemSelector).hide();}
function assignDeselect(that,container,tableID,table,options){container.find('a[data-options-deselect="'+tableID+'"]').off('click.textmagic').on('click.textmagic',function(e){options.deselectAllFunction(that);e.preventDefault();optionsTableToggle(table,'uncheck');table.data('checked',false);});}
(function($){$.prepareCrudPage=function(inputOptions){var crudApi,paginationApi,options,searchTimer,checkedItems=[],checkAllItems=false,defaultParams={};var defaultOptions={reloadAfterInit:true,containerSelector:'#crud-container',itemSelector:'tr[data-crud="item"]',dateListSelector:false,datePairSelector:false,commandUrl:'/online/crud/ajax',paginationCommand:'table',paginationScroll:false,paginationRecount:false,removeCommand:'remove',updateCommand:'update',container:$(this.containerSelector),perPage:10,spin:true,preSearchCallback:function(env){return true;},callbackRecount:function(r){var total=r.data.total;if(typeof $.fn.format==='function'){total=$.fn.format(total);}
var overlimit=r.data.overlimit;var totalStr=(typeof overlimit!=='undefined'&&overlimit)?'many':total;options.container.find('[data-crud-count="count"]').text(totalStr);var exportTotal=r.data.export_total;if(typeof exportTotal!=='undefined'){options.container.find('[data-crud-export-count]').attr('data-crud-export-count',exportTotal);}
var max=options.container.find('[data-crud-max="max"]');if(parseInt(max.text())>=r.data.total){max.text(r.data.total);options.container.find('ul.pager li.next').addClass('disabled').off('click');}
buttonEnable($('[data-options-recount]'));},removeFunction:function(env){if('console'in window){console.log('No remove function specified');}},bulkRemoveFunction:function(env){if('console'in window){console.log('No bulk remove function specified');}},updateFunction:function(env){if('console'in window){console.log('No update function specified');}},bulkUpdateFunction:function(env){if('console'in window){console.log('No bulk update function specified');}},updateCheckboxesFunction:function(env){var itemId=$(env).closest('tr').data('id');if($.inArray(itemId,checkedItems)!==-1){$(env).attr('checked',true);}else{$(env).attr('checked',false);}},togglePager:function(){var container=$(options.containerSelector),pager=container.find('ul.pager'),onPage=container.find('.pagin-panel select');if(checkAllItems===true){pager.addClass('disabled').addClass('text-muted');onPage.prop('disabled','disabled');}else{pager.removeClass('disabled').removeClass('text-muted');onPage.prop('disabled',false);}},checkboxChangeFunction:function(env){var itemId=$(env).closest('tr').data('id');if($(env).is(':checked')){checkedItems.pushOnce(itemId);}else{if(checkAllItems){checkAllItems=false;checkedItems=[];$(options.itemSelector).each(function(){if($(this).find('input[type="checkbox"]').is(':checked')){checkedItems.pushOnce($(this).data('id'));}});}else{checkedItems.popAll(itemId);}}
this.togglePager();},topCheckboxChangeFunction:function(env){var checked=$(env).is(':checked');if(checked){$(options.itemSelector).each(function(){checkedItems.pushOnce($(this).data('id'));});}else{$(options.itemSelector).each(function(){checkedItems.popAll($(this).data('id'));});crudApi.setCheckedAllItems(false);}
this.togglePager();},selectAllFunction:function(env){if($('input[name="search-query"]').val()){return false;}
checkAllItems=true;checkedItems=[];this.togglePager();},deselectAllFunction:function(env){checkAllItems=false;checkedItems=[];this.togglePager();},afterReloadFunction:function(env){return true;},beforeReloadFunction:function(env){return true;},checkedItemsChangeFunction:function(){return true;}};function loadDefaultParams(){if(inputOptions.commandUrl){paramsSection=inputOptions.commandUrl.replace(/\//gi,'_')+'_'+inputOptions.paginationCommand;}else if(defaultOptions.commandUrl){paramsSection=defaultOptions.commandUrl.replace(/\//gi,'_')+'_'+defaultOptions.paginationCommand;}else{if('console'in window){console.log('No section for load default params data');}
return false;}
params=Cookies.getJSON(paramsSection);if($.isPlainObject(params)){if(params.direction){defaultParams.direction=params.direction;}
if(params.orderBy){defaultParams.orderBy=params.orderBy;}
if(params.perPage){options.perPage=params.perPage;}}}
function saveDefaultParams(options){if(inputOptions.commandUrl){paramsSection=inputOptions.commandUrl.replace(/\//gi,'_')+'_'+inputOptions.paginationCommand;}else if(defaultOptions.commandUrl){paramsSection=defaultOptions.commandUrl.replace(/\//gi,'_')+'_'+defaultOptions.paginationCommand;}else{if('console'in window){console.log('No section for save default params data');}
return false;}
params={direction:options.requestParams.direction,orderBy:options.requestParams.orderBy,perPage:options.perPage};Cookies.set(paramsSection,params,{expires:365});}
function setOptions(inputOptions){options=$.extend({},defaultOptions,options,inputOptions);options.container=$(options.containerSelector);if(options.container.length==0){if('console'in window){console.log('No container found by '+options.containerSelector+', exiting');}
return false;}
loadDefaultParams();$('[data-crud="bulk-remove"]').off('click.crud').on('click.crud',function(){options.bulkRemoveFunction(this);});$('[data-crud="bulk-update"]').off('click.crud').on('click.crud',function(){options.bulkUpdateFunction(this);});paginationApi=initPagination();if(options.reloadAfterInit){paginationApi.reload();}}
function initPagination(){var container=options.container;var pagApi=container.widgetPagination({page:1,perPage:options.perPage,requestParams:$.extend({},defaultParams,{cmd:options.paginationCommand}),scroll:options.paginationScroll,recount:options.paginationRecount,callbackRecount:options.callbackRecount,callbackReloadBefore:function(api,requestParams){options.beforeReloadFunction(api);if(options.spin){spinIt(container,'enable');}
return;},callbackReloadSuccess:function(api){var table=container.find('table');table.find('input[type="checkbox"]').each(function(){if($(this).closest('tr').data('id')!=undefined){options.updateCheckboxesFunction(this);}});var tableID=table.attr('id'),$checks=table.find('tbody input[type="checkbox"]').not(':disabled'),count=$checks.filter(':checked').length,max=$checks.length,$all=table.find('thead input[type="checkbox"]'),$buttons=$('[data-options-table="'+tableID+'"]'),$emptyTableButtons=$('[data-options-empty-table="'+tableID+'"]'),$counter=$('[data-options-count="'+tableID+'"]'),rowsCount=table.find('tbody > tr[data-widget]').length,$selectAllSpan=table.find('span.select-all'),allSelectedEntries={'All':'','items':'item','are':'is'};optionsTableButtons($emptyTableButtons,rowsCount);optionsTableCheck($checks);optionsTableCount(crudApi,table,$all,$buttons,$counter,count,max);table.find('input[type="checkbox"]').off('change.crudapi').on('change.crudapi',function(){if($(this).closest('tr').data('id')!=undefined){options.checkboxChangeFunction(this);var $select=$('[data-options-select="'+tableID+'"]'),totalRowsCount=parseInt(($select.find('span.value').text().replace(/\D/g,'')),10);this.checked?count+=1:count-=1;if(crudApi.getCheckedItems().length===totalRowsCount){$select.click();if(totalRowsCount===1){rewriteSpanHtml($selectAllSpan,allSelectedEntries);assignDeselect(this,container,tableID,table,options);}}else{optionsTableCheck($(this));optionsTableCount(crudApi,table,$all,$buttons,$counter,count,max);}}});table.find('thead input[type="checkbox"]').on('change',function(){options.topCheckboxChangeFunction(this);var $select=$('[data-options-select="'+tableID+'"]'),totalRowsCount=parseInt($select.find('span.value').text().replace(/\D/g,''),10);count=0;if(this.checked){$checks.prop('checked',true);count=$checks.length;}else{$checks.prop('checked',false);}
optionsTableCheck($checks);optionsTableCount(crudApi,table,$(this),$buttons,$counter,count,max);if(crudApi.getCheckedItems().length===totalRowsCount){$select.click();this.checked=true;if(totalRowsCount===1){rewriteSpanHtml($selectAllSpan,allSelectedEntries);assignDeselect(this,container,tableID,table,options);}}});container.find('a[data-crud="remove"]').on('click',function(){options.removeFunction(this);});container.find('a[data-crud="update"]').on('click',function(){options.updateFunction(this);});container.find('a[data-options-select="'+tableID+'"]').off('click.textmagic').on('click.textmagic',function(e){options.selectAllFunction(this);e.preventDefault();optionsTableToggle(table,'check');table.data('checked','all');$(this).closest($buttons).addClass('selected');});assignDeselect(this,container,tableID,table,options);container.find('th[data-field]').on('click.crudSort',function(e){e.preventDefault();var orderBy=$(this).data('field');var oldOrderBy=api.getOptions().requestParams.orderBy;var direction='asc';if(orderBy==oldOrderBy){direction=($(this).hasClass('headerSortUp'))?'desc':'asc';}
var params=api.getOptions().requestParams.params;api.setOptions({requestParams:{cmd:options.paginationCommand,orderBy:orderBy,direction:direction,params:params}}).setRequestParams({}).reload();});if(options.spin){spinIt(container,'disable');}
appendNoResults(table);saveDefaultParams(api.getOptions());options.afterReloadFunction();syncOptionsTableButtons();return;},callbackReloadError:function(api,data){if(options.spin){spinIt(container,'disable');}
options.afterReloadFunction(api,data);}},function(api){initSearchWidget(searchTimer,api,options.searchFormSelector,options.dateListSelector,options.datePairSelector,options.searchAfterInit,options.preSearchCallback);if(!options.dontInitExport){initExportWidget(api,'a.export-lnk');}
initDateFilterWidget();return;});return pagApi;}
setOptions(inputOptions);crudApi={getPaginationApi:function(){return paginationApi;},getOptions:function(){return options;},setOptions:setOptions,disableSpin:function(){options.spin=false;},enableSpin:function(){options.spin=true;},getCheckedItems:function(){return checkedItems;},setCheckedItems:function(items){checkedItems=[];this.addCheckedItems(items);options.checkedItemsChangeFunction();return this.getCheckedItems();},addCheckedItems:function(items){for(var i=0;i<items.length;i++){checkedItems.pushOnce(items[i]);}
options.checkedItemsChangeFunction();return this.getCheckedItems();},removeCheckedItems:function(items){for(var i=0;i<items.length;i++){checkedItems.popAll(items[i]);}
options.checkedItemsChangeFunction();return this.getCheckedItems();},getCheckedAllItems:function(){return checkAllItems;},setCheckedAllItems:function(flag){checkAllItems=flag;options.checkedItemsChangeFunction();return this.getCheckedAllItems();},post:function(data,deferredCallback){$.post(options.commandUrl,data).done(function(r){if(deferredCallback){deferredCallback(r);}
return r;}).fail(function(){return false;});},removeItems:function(ids,deferredCallback){var removeOptions={cmd:options.removeCommand,ids:ids,params:paginationApi.getRequestParams()['params']};checkedItems=[];checkAllItems=false;if(deferredCallback){this.post(removeOptions,deferredCallback);}else{$.when(this.post(removeOptions)).then(paginationApi.reload());}},updateItems:function(ids,field,value,deferredCallback){var updateOptions={cmd:options.updateCommand,ids:ids,field:field,value:value};checkedItems=[];checkAllItems=false;if(deferredCallback){this.post(updateOptions,deferredCallback);}else{$.when(this.post(updateOptions)).then(paginationApi.reload());}}};return crudApi;};$.simpleEmailValidate=function(email){var re=/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;return re.test(email);};$.confirmDefferedExport=function(params){var randId=Math.floor(Math.random()*1000000);var defaultParameters={title:'Send the download link to an email',message:'Export of data can take some time. Please enter email address, and we will send a download link as soon as possible.'};var params=$.extend({},defaultParameters,params);var csrfToken=$('meta[name="csrf-token"]').attr('content');var markup=['<div id="defferedExportModal_'+randId+'" class="modal modal-sm fade" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="false">','<div class="modal-dialog">','<div class="modal-content">','<div class="modal-body text-center">','<h2>'+params.title+'</h2>','<p>'+params.message+'</p>','<div class="form-group">','<input class="form-control" type="text" name="export_email"/>','</div>','<p class="confirmModalButtons">','<button class="btn btn-default" type="button" data-dismiss="modal" data-crud="export-cancel">Cancel</button>','<button class="btn btn-success btn-solid disabled" type="button" data-crud="send-export">Send</button>','</p>','</div>','</div>','</div>','</div>'].join('');$(markup).hide().appendTo('body').modal('show');var modalWindow=$('#defferedExportModal_'+randId);var exportBtn=$('button[data-crud="send-export"]');exportBtn.btn('disable');var email=typeof(app.u_email)!=='undefined'?app.u_email:'';modalWindow.find('input[name="export_email"]').val(email).focus();modalWindow.find('button[data-crud="send-export"]').on('click',function(){var that=this;var last=params.last;var $exportLnk=params.exportLnk;var email=modalWindow.find('input[name="export_email"]').val();var counter=$('[data-crud-export-count]');var $topAlert=$('[data-widget="top-alert"]');var $cancelBtn=$('[data-crud="export-cancel"]');if(app.data.user&&app.data.user.exportDisabled){$topAlert.warningBlock(msgExportDisabled);modalWindow.modal('hide');return false;}
if(counter.length&&parseInt(counter.attr('data-crud-export-count'))>params.maxExport){$topAlert.warningBlock('Your exported file is too large. Please contact support to get the requested file.');modalWindow.modal('hide');return false;}
last.defExport=true;last.exportEmail=encodeURIComponent(email);delete last.page;var query=decodeURIComponent($.param(last));var url=$exportLnk.attr('href');var paramSign=(url.indexOf('?')>0)?'&':'?';url=url+paramSign+query;if(url.includes('messages_sent_ajax')||url.includes('contacts_ajax')){url=url+'&_csrf_token='+encodeURIComponent(csrfToken);}
$.ajax({beforeSend:function(){$cancelBtn.prop('disabled',true);$(that).spin('enable','Sending...');},method:'GET',url:url,success:function(xhr){$(that).spin('disable');$cancelBtn.prop('disabled',false);modalWindow.modal('hide');$topAlert.successBlock('Your data is now being prepared for download. We will send a download link to your email address as soon as possible.');},error:function(xhr){$(that).spin('disable');$cancelBtn.prop('disabled',false);modalWindow.modal('hide');$topAlert.warningBlock('Sorry, but it looks like something has gone wrong. Please try again or contact us at support@textmagic.com.');}});});modalWindow.find('input[name="export_email"]').on('input change click keyup blur focus',function(){var email=$(this).val();if($.simpleEmailValidate(email)){exportBtn.btn('enable');}else{exportBtn.btn('disable');}});};$.confirmDeleteAll=function(params){var randId=Math.floor(Math.random()*1000000);var defaultParameters={title:'Delete all items',message:'To delete all items, please enter '+this.confirmText+' here',confirmText:'DELETE MY ITEMS',deleteButtonText:'Delete',cancelButtonText:'Cancel',deleteButtonCallback:function(){},cancelButtonCallback:function(){}};params=$.extend({},defaultParameters,params);var markup=['<div id="confirmAllModal_'+randId+'" class="modal modal-sm fade" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="false">','<div class="modal-dialog">','<div class="modal-content">','<div class="modal-body text-center">','<h2>'+params.title+'</h2>','<p>'+params.message+'</p>','<p class="confirmModalButtons">','<button class="btn btn-default" type="button" data-dismiss="modal" data-crud="cancel">'+params.cancelButtonText+'</button>','<button class="btn btn-danger disabled" type="button" data-crud="remove-all-items">'+params.deleteButtonText+'</button>','</p>','</div>','</div>','</div>','</div>'].join('');$(markup).hide().appendTo('body').modal('show');var modalWindow=$('#confirmAllModal_'+randId);modalWindow.find('button[data-crud="remove-all-items"]').on('click.confirmDeleteAll',function(e){e.preventDefault();$(this).spin('enable');$(this).siblings('[data-dismiss]').btn('disable');params.deleteButtonCallback();if(typeof params.preventModalHide==='undefined'){modalWindow.modal('hide');modalWindow.remove();}});modalWindow.find('button[data-crud="cancel"]').on('click.confirmDeleteAll',function(e){e.preventDefault();params.cancelButtonCallback();modalWindow.modal('hide');modalWindow.remove();});}
$.confirmInp=function(params){var defaultParameters={title:'Do action',message:'Are you sure you would like to do this action?',yesButtonText:'Do action',cancelButtonText:'Cancel',modalId:'confirmWithInput_'+Math.floor(Math.random()*1000000),inp_name:null,inp_placeholder:null,yesButtonCallback:function(){},cancelButtonCallback:function(){}};params=$.extend({},defaultParameters,params);var input;if(params.inp_name){input='<div class="form-group">'+
'<input class="form-control" type="text" '+'name="'+params.inp_name+'" placeholder="'+params.inp_placeholder+'" />'+
'</div>';}
var markup=['<div id="'+params.modalId+'" class="modal modal-sm fade" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="false">','<div class="modal-dialog">','<div class="modal-content">','<div class="modal-body text-center">','<h2>'+params.title+'</h2>','<p>'+params.message+'</p>','<div class="form-group">','<input class="form-control" type="text" name="confirmation_text" placeholder="Enter password" autocomplete="off"/>','</div>',input,'<p class="confirmModalButtons">','<button class="btn btn-default" type="button" data-dismiss="modal" data-crud="confirm-cancel-btn">'+params.cancelButtonText+'</button>','<button class="btn btn-danger" type="button" data-crud="confirm-yes-btn">'+params.yesButtonText+'</button>','</p>','</div>','</div>','</div>','</div>'].join('');$(markup).hide().appendTo('body').modal('show');var modalWindow=$('#'+params.modalId);modalWindow.find('button[data-crud="confirm-yes-btn"]').on('click',function(e){e.preventDefault();$(this).spin('enable','Processing...');$(this).siblings('[data-dismiss]').btn('disable');params.yesButtonCallback();if(typeof params.preventModalHide==='undefined'){modalWindow.modal('hide');modalWindow.remove();}});modalWindow.find('button[data-crud="confirm-cancel-btn"]').on('click',function(e){e.preventDefault();params.cancelButtonCallback();modalWindow.modal('hide');modalWindow.remove();});}})(jQuery);